config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
	 
  resources :players, :results do
  	resources :players, :results
  end
root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/models/match.rb
class Match < ApplicationRecord
	has_many :results
	has_many :players, through: :results 
end

app/models/player.rb
class Player < ApplicationRecord
	has_many :results
	validates :name, presence: true, length: {maximum: 100}
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :player

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
	def index
		@players = Player.all
	end

	def show
		@player = Player.find(params[:id])
	end

	def new
		@player = Player.new
	end

	def create
		@player = Player.new(player_params)

		if @player.save
			redirect_to @player
		else
			render 'new'
		end
	end

	def destroy
		@player = Player.find(params[:id])
		@player.destroy

		redirect_to players_path
	end

	private
	def player_params
		params.require(:player).permit(:name, :win, :draw, :lose, 
			:gs, :gt, :dr, :points)
	end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
	def index
		@results = Result.all
	end

	def show
		@result = Result.find(params[:id])
	end

	def new
		@result = Result.new
	end

	def create
		@result = Result.new(result_params)

		if @result.save
			redirect_to @result
		else
			render 'new'
		end
	end

	def destroy
		@result = Result.find(params[:id])
		@result.destroy

		redirect_to results_path
	end

	private
		def result_params
			params.require(:result).permit(:name1, :goal1, :name2, :goal2,
				:date, :player_id)
		end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "STORE YOUR RESULTS", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
          <%= link_to "Players", players_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Board", players_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
          <li class="nav-item">
            <%= link_to "Results", results_path, class: "nav-link" %>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Results</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
     <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
<footer> Copyright &copy; Results 2020 - All rights reserved <%= link_to "Simone Piazzini", "https://github.com/axis93", class: "text-white" %> </footer>

</html>

app/views/players/edit.html.erb
<h1>Edit Player</h1>

app/views/players/index.html.erb
<div id="page-content">
	<h1 class="text-center mt-4">Listing all the Players</h1>
	<%= link_to 'Add a Player', new_player_path %>
	<%= link_to 'Add result', new_result_path %>
	<%= link_to 'Show Results', results_path %>

	<div class="container">
	<% @players.each do |player| %>
		<div class="row justify-content-md-center">
			<div class="col-6">
				<div class="card border-secondary mb-1 shadow p-1 mb-5 bg-white rounded" >
					<h5 class="card-title card-header"> <%= link_to player.name, player_path(player), class: "text-primary" %></h5>
						<div class="card-body">
							<p class="card-text"> <strong>Points: </strong> <%= player.points %> win :<%= player.win %> draw <%= player.draw %> lose <%= player.lose %> GS: <%= player.gs %> GT: <%= player.gt %> DR: <%= player.dr %> </p>
							<%= link_to 'View', player_path(player), class: "btn btn-primary" %>
							<%= link_to 'Delete', player_path(player), class: "btn btn-primary", method: :delete, data: {confirm: "Are you sure?"} %>
						</div>
				</div>		
			</div>
		</div>
	<% end %>
	</div>
</div>	

app/views/players/new.html.erb
<h1>New Player</h1>

<% if @player.errors.any? %>
	<h2>The following errors prevented the player to be saved</h2>
	<ul>
		<% @player.errors.full_messages.each do |msg| %>
			<li><%= msg %> </li>
	<% end %>
	</ul>
<% end %>

<%= form_with scope: :player, url: players_path, local: true do |form| %>
	<p>
		<%= form.label :name %>
		<%= form.text_field :name %>
	</p>
	<p>
		<%= form.label :win %>
		<%= form.text_field :win %>
	</p>
	<p>
		<%= form.label :draw %>
		<%= form.text_field :draw %>
	</p>
	<p>
		<%= form.label :lose %>
		<%= form.text_field :lose %>
	</p>
	<p>
		<%= form.label :gs %>
		<%= form.text_field :gs %>
	</p>
	<p>
		<%= form.label :gt %>
		<%= form.text_field :gt %>
	</p>
	<p>
		<%= form.label :dr %>
		<%= form.text_field :dr %>
	</p>
	<p>
		<%= form.label :points %>
		<%= form.text_field :points %>
	</p>
	<p>
		<%= form.submit %>
	</p>
<% end %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<div id="page-content">
	<h1 class="text-center mt-4">Listing all the Players</h1>
	<%= link_to 'Add a Player', new_player_path %>
	<%= link_to 'Add result', new_result_path %>
	<%= link_to 'Show Results', results_path %>

	<div class="container">
	<% @players.each do |player| %>
		<div class="row justify-content-md-center">
			<div class="col-6">
				<div class="card border-secondary mb-1 shadow p-1 mb-5 bg-white rounded" >
					<h5 class="card-title card-header"> <%= link_to player.name, player_path(player), class: "text-primary" %></h5>
						<div class="card-body">
							<p class="card-text"> <strong>Points: </strong> <%= player.points %></p>
							<%= link_to 'View', player_path(player), class: "btn btn-primary" %>
							<%= link_to 'Delete', player_path(player), class: "btn btn-primary", method: :delete, data: {confirm: "Are you sure?"} %>
						</div>
				</div>		
			</div>
		</div>
	<% end %>
	</div>
</div>	

app/views/results/index.html.erb
<div id="page-content">
<h1 class="text-center p-4">This is the list of all the result</h1>
<%= link_to 'Back to the Board', players_path %>
<%= link_to 'Add a new result', new_result_path %>

<div class="container">
	<% @results.each do |result| %>
	<div class="row justify-content-md-center">
		<div class="col-6">
			<div class="card border-secondary mb-1 shadow p-1 mb-5 bg-white rounded">
				<h5 class="card-title card-header bg-secondary text-center"> <%= result.date %></h5>
				<div class="card-body text-center">
					<p class="card-text text-center"> <strong> <%= result.name1 %> </strong> <%= result.goal1 %> - <%= result.goal2 %> <strong> <%= result.name2 %> </strong>
						
					</p>
					<%= link_to 'Destroy', result_path(result), class: "btn btn-primary  float-bottom btn-sm", method: :delete, data: {confirm: '
		Are you sure?'} %>
				</div>
			</div>
		</div>		
	</div>





<% end %>
</div>

</div>

app/views/results/new.html.erb
<h1>New Result</h1>
<%= form_with scope: :result, url: results_path, local: true do |form| %>
<h2>Add a result:</h2>
<div id="add_result">
<p>
	<%= form.label :name %>
	<%= form.text_field :name1 %>
</p>

<p>
	<%= form.label :goal %>
	<%= form.text_field :goal1 %>
</p>

<p>
	<%= form.label :name %>
	<%= form.text_field :name2 %>
</p>

<p>
	<%= form.label :goal %>
	<%= form.text_field :goal2 %>
</p>
<p>
	<%= form.label :date %>
	<%= form.text_field :date %>
</p>

<p>
	<%= form.text_field :player_id %>
  
<p>
		<%= form.submit %>
</p>
</div>
<% end %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p>
	<strong>Name: </strong>
	<%= @result.name1 %>
	<%= @result.goal1 %>
	<strong> - </strong>
	<%= @result.goal2 %>

</p>


<%= link_to 'Back', results_path %>

app/views/welcome/index.html.erb
<div id="page-content">
	<div class="container" id="home">
		<div class="jumbotron">
		  <h1 class="display-4">Hello, world!</h1>
		  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
		  <hr class="my-4">
		  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
		  <a class="btn btn-primary btn-lg" href="#" role="button">Sign up</a>
		</div>
	</div>	
</div>

<footer> Copyright &copy; Results 2020 - All rights reserved   </footer>